(1) Add 'run-docker-login' parameter (2) Explicitly specify --profile on all aws commands (3) Minor cleanup/refactor

diff --git a/bin/fargate-deploy b/bin/fargate-deploy
--- a/bin/fargate-deploy
+++ b/bin/fargate-deploy
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
 usage() {
-  bold=$(tput bold)
-  normal=$(tput sgr0)
+  local bold=$(tput bold)
+  local normal=$(tput sgr0)
   echo ""
   echo "${bold}NAME${normal}"
   echo -e "\t$(basename $0)"
@@ -23,6 +23,7 @@ usage() {
   echo -e "\t[--aws-profile <value>]"
   echo -e "\t[--image-name <value>]"
   echo -e "\t[--image-tag <value>]"
+  echo -e "\t[--run-docker-login]"
   echo -e "\t[--parameter-overrides <value> [<value>...]]"
   echo ""
   echo "${bold}OPTIONS${normal}"
@@ -36,6 +37,9 @@ usage() {
   echo -e "\t${bold}--image-name${normal} (string) The (optional) name of the Docker image to deploy (defaults to task-name)"
   echo ""
   echo -e "\t${bold}--image-tag${normal} (string) The (optional) tag of the Docker image to deploy (defaults to current Git revision)"
+  echo ""
+  echo -e "\t${bold}--run-docker-login${normal} Explicitly run 'docker login' command to authenticate to ECR.  Intended for systems"
+  echo -e "\t  which don't have the 'Docker Amazon ECR Docker Credential Helper' installed.  (May generate security warnings.)"
   echo ""
   echo -e "\t${bold}--parameter-overrides${normal} (list) An (optionals) list of parameter structures which will override default"
   echo -e "\t  template values.  Syntax: ParameterKey1=ParameterValue1 ParameterKey2=ParameterValue2 ..."
@@ -62,6 +66,21 @@ git_check() {
   fi
 }
 
+docker_login() {
+  if (( ${RunDockerLogin} == 1 )); then
+    echo "Logging in to ECR: ${EcrRepository}"
+    $(aws --profile ${AwsProfile} ecr get-login --no-include-email --region ${AwsRegion})
+  fi
+}
+
+docker_logout() {
+  if (( ${RunDockerLogin} == 1 )); then
+    echo "Logging out of ECR: : ${EcrRepository}"
+    docker logout ${EcrRepository}
+  fi
+}
+
+
 # Get script info
 ScriptDirectory=$(dirname $0)
 ScriptName=$(basename $0 )
@@ -72,6 +91,7 @@ DeploymentEnvironment=
 AwsProfile=
 ImageName=
 ImageTag=
+RunDockerLogin=0
 ParameterOverrides=
 
 Params=""
@@ -89,6 +109,10 @@ while (( "$#" )); do
     --aws-profile)
       AwsProfile=$2
       shift 2
+      ;;
+    --run-docker-login)
+      RunDockerLogin=1
+      shift
       ;;
     --parameter-overrides)
       shift
@@ -150,13 +174,23 @@ EcrImageTag=${ImageTag}
 
 echo "Pushing to ${EcrImageName} to ECR"
 docker tag ${LocalImageName}:${LocalImageTag} ${EcrImageName}:${EcrImageTag}
+
+docker_login
 docker push ${EcrImageName}:${EcrImageTag}
+if [[ $? -ne 0 ]]; then
+    echo "ERROR: Unable to push ${EcrImageName}:${EcrImageTag} to ECR -- aborting!"
+    docker_logout
+    exit 1
+fi
+
+docker_logout
 
 # Deploy service
 TemplateFile=${ScriptDirectory}/${ScriptName}-cf.yaml
 DeploymentEnvironmentProperties=$(cat ${ScriptDirectory}/${ScriptName}-${DeploymentEnvironment}.properties)
 
-aws cloudformation deploy \
+aws --profile ${AwsProfile} \
+cloudformation deploy \
   --stack-name ${TaskName}-${DeploymentEnvironment}-stack \
   --template-file ${TemplateFile} \
   --parameter-overrides ${DeploymentEnvironmentProperties} \
